### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by redtux** [redtux/redtux#2]
# Version 0.1.0

## Copyright

- Copyright (c) 2021 Pablo Hörtner. All rights reserved.
- This project is released under the terms of the [GNU Affero General Public License](https://spdx.org/licenses/AGPL-3.0-or-later.html).
- The documentation in `docs` and `_posts` is released under the terms of the [Creative Commons Attribution-ShareAlike](https://spdx.org/licenses/CC-BY-NC-SA-4.0.html).

## Task list

- [ ] feat: initial commit
- [ ] docs: add readme
- [ ] chore(deps): add gem dependencies
- [ ] feat: set project license to agpl-3.0-or-later
- [ ] docs: set documentation license to cc-by-sa-4.0
- [ ] chore(conf): add jekyll config
- [ ] docs: add default index.html
- [ ] docs: add example blog post
- [ ] feat(seo): add robots.txt
- [ ] feat(seo): add error 404 page
- [ ] feat(seo): add favicon
- [ ] docs: add code of conduct
- [ ] docs: add contributing guidelines
- [ ] feat: add layouts
- [ ] feat: add gemspec
- [ ] feat: add bootstrap css
- [ ] feat: add mdb css
